all: Convolution.cpp
	g++ Convolution.cpp -o assignment -lOpenCL -std=c++11 #-I/usr/local/cuda-8.0/targets/x86_64-linux/include
	# uncomment the include above for building on vocareum, it causes problems on my local machine though.
